import { useState } from "react";
import { Sparkles, Send, Copy, Check } from "lucide-react";
import { Modal, Button, Badge } from "./ui";
import api, { apiError } from "../lib/api";
import { toast } from "sonner";

const TONES = [
  { key: "professional", label: "Professional" },
  { key: "persuasive", label: "Persuasive" },
  { key: "casual", label: "Casual" },
];

export default function EmailDraftModal({ deal, onClose }) {
  const [tone, setTone] = useState("professional");
  const [draft, setDraft] = useState(null);
  const [loading, setLoading] = useState(false);
  const [sending, setSending] = useState(false);
  const [copied, setCopied] = useState(false);
  const [to, setTo] = useState("");

  const generate = async (t) => {
    setTone(t);
    setLoading(true);
    try {
      const { data } = await api.post("/ai/email/draft", { deal_id: deal.id, tone: t });
      setDraft(data.data);
      setTo(data.data.to_email || "");
      toast.success("Draft generated");
    } catch (e) {
      toast.error(apiError(e.response?.data?.detail));
    } finally {
      setLoading(false);
    }
  };

  const copy = () => {
    navigator.clipboard.writeText(`${draft.subject}\n\n${draft.body}`);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  const send = async () => {
    setSending(true);
    try {
      const { data } = await api.post("/ai/email/send", {
        deal_id: deal.id, to_email: to, subject: draft.subject, body: draft.body,
      });
      if (data.data.sent) toast.success(`Email sent to ${to}`);
      else toast.message("Email queued (demo mode)", { description: data.data.error || "Configure a verified Resend domain to deliver." });
    } catch (e) {
      toast.error(apiError(e.response?.data?.detail));
    } finally {
      setSending(false);
    }
  };

  return (
    <Modal open onClose={onClose} title="AI Email Drafter" testid="ai-email-draft-modal">
      <div className="mb-4">
        <div className="text-sm text-slate-400 mb-1">Follow-up for</div>
        <div className="font-medium text-white">{deal.title}</div>
      </div>

      <div className="flex gap-2 mb-4">
        {TONES.map((t) => (
          <button
            key={t.key}
            onClick={() => generate(t.key)}
            data-testid={`tone-${t.key}`}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-all ${
              tone === t.key ? "bg-accent/15 text-indigo-300 border-accent/40" : "bg-slate-800 text-slate-400 border-slate-700 hover:text-white"
            }`}
          >
            {t.label}
          </button>
        ))}
      </div>

      {!draft && !loading && (
        <Button onClick={() => generate(tone)} className="w-full" testid="generate-draft-btn">
          <Sparkles size={15} /> Generate draft
        </Button>
      )}

      {loading && (
        <div className="space-y-2">
          <div className="skeleton h-4 rounded w-1/2" />
          <div className="skeleton h-24 rounded w-full" />
        </div>
      )}

      {draft && !loading && (
        <div className="fade-up">
          <div className="mb-3">
            <div className="text-xs text-slate-500 uppercase tracking-wider mb-1">Subject</div>
            <input
              value={draft.subject}
              onChange={(e) => setDraft({ ...draft, subject: e.target.value })}
              data-testid="draft-subject"
              className="w-full bg-ink border border-slate-700 rounded-lg px-3 py-2 text-sm"
            />
          </div>
          <textarea
            value={draft.body}
            onChange={(e) => setDraft({ ...draft, body: e.target.value })}
            data-testid="draft-body"
            rows={7}
            className="w-full bg-ink border border-slate-700 rounded-lg px-3 py-2 text-sm mb-3 resize-none"
          />
          <div className="flex items-center gap-2 mb-4">
            <span className="text-xs text-slate-500">To:</span>
            <input
              value={to}
              onChange={(e) => setTo(e.target.value)}
              data-testid="draft-to-email"
              placeholder="recipient@email.com"
              className="flex-1 bg-ink border border-slate-700 rounded-lg px-3 py-2 text-sm"
            />
          </div>
          <div className="flex gap-2">
            <Button variant="ghost" onClick={copy} testid="copy-draft-btn">
              {copied ? <Check size={15} /> : <Copy size={15} />} {copied ? "Copied" : "Copy"}
            </Button>
            <Button onClick={send} disabled={sending || !to} className="flex-1" testid="send-email-btn">
              <Send size={15} /> {sending ? "Sending…" : "Send email"}
            </Button>
          </div>
          <div className="mt-3">
            <Badge color="violet">Generated by Qwen3 · Groq</Badge>
          </div>
        </div>
      )}
    </Modal>
  );
}
